function sparcodemo

demolist = {};

demolist{end+1} = {'Sparco problems', ...
                   'This script provides an explanation of how to use Sparco test problems', ...
                   'demo001.m'};
    
demolist{end+1} = {'Sparco operators', ...
                   'This script provides an explanation of how to use Sparco operators', ...
                   'demo002.m'};

demolist{end+1} = {'demo', ...
                   {'This demo illustrates the demo framework','for details see the demo1b.m file'}, ...
                   'demo1b.m'};

demolist{end+1} = {'DCT-Dirac construct', ...
                   {'Construct DCT-Dirac sparsity basis and Gaussian measurement matrix.'}, ...
                   'demo1a.m'};

demoFrame(demolist,'Sparco Demo');
